apiVersion: apps/v1
kind: Deployment
metadata:
  name: biotech-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: biotech-helloworld
        image: arsls/devops_biotech:latest
        ports:
        - containerPort: 32777
